name: PhyModels
version: '1.0-SNAPSHOT'
main: com.wiyuka.phymodels.PhyModels
api-version: '1.21'
folia-supported: true
commands:
  addmodel:

  generatemodel:

  addscript:

  scriptstart:

  removemodel:

  toggledebug:

  phyperform:

  modelinfo:

  cloth:


